<a href="https://colab.research.google.com/github/cmskzhan/helloworld/blob/master/concepts/plot_vwap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# https://polygon.io/docs/get_v2_aggs_ticker__stocksTicker__range__multiplier___timespan___from___to__anchor
import requests
import datetime
import json
import base64
import string
import pandas as pd
import numpy as np
import pickle
'''
Getting polygon ohlc, vwap and volume requires symbol, date range, etc
'''


# BASE_URL = "https://api.polygon.io/v2/aggs/ticker/"
url=r"https://api.polygon.io/v2/aggs"
cccccccx = 'Maya5pro+=='
symbol="GS"
multiplier=1
timespan="day"
from_date="2019-01-01"
to_date=datetime.date.today()
vw_url = f"/ticker/{symbol}/range/{multiplier}/{timespan}/{from_date}/{to_date}"
cccccccz = cccccccx + string.ascii_letters[:1:-3] + string.hexdigits[6:12:2]
full_url = url + vw_url
pd.set_option("display.precision", 4)

column_names = { 
"v": "Volume",
"vw": "VWAP",
"o": "Open",
"c": "Adj Close",
"h": "High",
"l": "Low",
"n": "transactions"
  }

In [3]:
def dccc(key, ring):
    ring = base64.urlsafe_b64decode(ring + b'===')
    ring = ring.decode('latin')
    encoded_chars = []
    for i in range(len(ring)):
        key_c = key[i % len(key)]
        encoded_c = chr((ord(ring[i]) - ord(key_c) + 256) % 256)
        encoded_chars.append(encoded_c)
    e_string = ''.join(encoded_chars)
    return e_string

AK = dccc(cccccccz, pickle.loads(requests.get("https://github.com/cmskzhan/helloworld/raw/master/pgon.pik").content))
data = { "apikey": AK, "sort": "asc", "limit": 50000 }

In [4]:

response = requests.get(full_url, data)

parsed = json.loads(response.text)

df_polygon = pd.DataFrame.from_dict(parsed['results'])
df_polygon["Date"] = pd.to_datetime(df_polygon['t']/1000, unit='s').dt.date
df_polygon = df_polygon.rename(columns=column_names)
df_polygon.set_index('Date', inplace=True)
df_polygon.index=pd.to_datetime(df_polygon.index)
df_polygon.drop('t', axis=1, inplace=True)
df_polygon

,Volume,VWAP,Open,Adj Close,High,Low,transactions
Date,,,,,,,
2023-12-28,1024818.0,386.4419,384.520,386.41,387.7600,383.6300,29216
2023-12-29,881319.0,385.5126,385.570,385.77,386.6400,383.5700,23439
2024-01-02,2263330.0,387.2380,383.000,388.30,389.1400,382.1900,42092
2024-01-03,2265306.0,381.1161,383.880,381.79,385.3950,376.7633,43741
2024-01-04,1618314.0,383.8197,383.550,382.95,387.0899,381.9500,30402
...,...,...,...,...,...,...,...
2025-12-19,4808303.0,892.6506,883.170,893.48,899.7475,881.9510,71957
2025-12-22,1442332.0,900.1824,896.520,899.00,905.4800,894.8400,52832
2025-12-23,1210438.0,901.4546,900.345,901.71,905.9200,893.7000,46005
2025-12-24,771780.0,908.1392,901.160,910.78,911.8800,898.7000,27646
2025-12-26,1037343.0,907.8832,911.000,907.04,913.3175,905.3050,43093

In [5]:

def VWAP_WSTD_BB(df, span_window, std_weight):
    df['VWAP_EMA'] = df['VWAP'].ewm(span=span_window, min_periods=span_window/2).mean() #draw a VWAP EMA line
    df['VWAP_WSTD'] = df['VWAP_EMA'].rolling(window=span_window).std()*std_weight # calculate sigma (std) * weight

    return df['VWAP_EMA'] + df['VWAP_WSTD'], df['VWAP_EMA'] - df['VWAP_WSTD']

# df_polygon['VWAP_EMA26'] = df_polygon['VWAP'].ewm(span=26, min_periods=10).mean()
# df_polygon['VWAP_WSTD'] = df_polygon['VWAP_EMA26'].rolling(window=26).std()*2.2

UPPER, LOWER = VWAP_WSTD_BB(df_polygon, 26, 2.2)
df_polygon.tail(10)

,Volume,VWAP,Open,Adj Close,High,Low,transactions,VWAP_EMA,VWAP_WSTD
Date,,,,,,,,,
2025-12-12,2715200.0,895.9510,913.750,887.96,914.9900,886.9900,97712,831.4158,30.8514
2025-12-15,1976603.0,894.0219,892.000,889.59,904.4700,889.5900,73996,836.0533,34.6804
2025-12-16,2161603.0,881.8391,890.230,879.15,896.2400,874.3200,80918,839.4448,38.1535
2025-12-17,2213336.0,876.0579,886.330,872.33,895.9700,868.4410,75096,842.1569,41.3247
2025-12-18,2066338.0,881.8337,880.500,876.30,892.7850,874.6975,77169,845.0959,44.3353
2025-12-19,4808303.0,892.6506,883.170,893.48,899.7475,881.9510,71957,848.6185,47.4688
2025-12-22,1442332.0,900.1824,896.520,899.00,905.4800,894.8400,52832,852.4380,50.6342
2025-12-23,1210438.0,901.4546,900.345,901.71,905.9200,893.7000,46005,856.0689,53.6331
2025-12-24,771780.0,908.1392,901.160,910.78,911.8800,898.7000,27646,859.9259,56.4058
2025-12-26,1037343.0,907.8832,911.000,907.04,913.3175,905.3050,43093,863.4783,58.8478

In [6]:
import plotly.graph_objects as go
# 准备画布
fig = go.Figure()

fig = go.Figure(data=go.Ohlc(x=df_polygon.index,
                    open=df_polygon['Open'],
                    high=df_polygon['High'],
                    low=df_polygon['Low'],
                    close=df_polygon['Adj Close'],
                    name='K-chart'))


fig.add_trace(go.Scatter(  # 
    x=UPPER.index, 
    y=UPPER,               
    mode='lines', # line mode          
    name='UPPER Band',
    line=dict(color='royalblue', width=0.5))) # or color='#00ffff'

fig.add_trace(go.Scatter(  # 
    x=df_polygon.index, 
    y=LOWER,               
    mode='lines', # line mode              
    name='LOWER Band',
    line=dict(color='firebrick', width=0.5))) # or color='#0000ff'

fig.show()

Initial stop loss ratio analysis

In [7]:
daily_volatility = (df_polygon['High'] - df_polygon['Low'])/df_polygon['Low']
initial_dailyVol_pertentage = np.percentile(daily_volatility, [70, 75, 80]).mean()

In [8]:
df_hl = df_polygon[['High','Low']]
df_hl.head(20)

                High       Low
Date
2023-12-28  387.7600  383.6300
2023-12-29  386.6400  383.5700
2024-01-02  389.1400  382.1900
2024-01-03  385.3950  376.7633
2024-01-04  387.0899  381.9500
2024-01-05  389.4700  381.0800
2024-01-08  389.0800  382.0250
2024-01-09  385.9500  381.7700
2024-01-10  383.0500  378.5300
2024-01-11  380.9800  374.6800
2024-01-12  385.8450  376.5800
2024-01-16  385.0100  374.3200
2024-01-17  380.2000  374.1300
2024-01-18  381.6400  374.5600
2024-01-19  383.3000  372.0700
2024-01-22  392.7300  384.5600
2024-01-23  383.3600  378.6250
2024-01-24  384.6100  379.1800
2024-01-25  386.7099  382.0100
2024-01-26  380.9000  376.7500

In [10]:
def iterate_high_low(df_hl:pd.DataFrame, rows:int, overlap=True):
  """iterate multi lines to get Max of High and Mimimum of Lows across multiple days

  df: DataFrame - required
  rows: int - lines of values to compare for Max/Min value, rows > 1
  overlap: boolean - True for rolling comparison, False for block comparison 
  """
  high = []
  low = []

  if overlap:
    for i in [df_hl.iloc[pos:pos+rows] for pos in range(0, len(df_hl)-1)]:
      high.append(max(i['High']))
      low.append(min(i['Low']))
  else:
    for i, g in df_hl.groupby(np.arange(len(df_hl)) // rows):
      high.append(g['High'].max())
      low.append(g['Low'].min())
  
  return high, low

In [11]:
hh, ll = iterate_high_low(df_polygon, 2)
ll[0:10]

[383.57,
 382.19,
 376.7633,
 376.7633,
 381.08,
 381.08,
 381.77,
 378.53,
 374.68,
 374.68]

In [12]:
df_lh = pd.DataFrame()
df_lh['low'] = ll
df_lh['high'] = hh
df_lh

          low      high
0    383.5700  387.7600
1    382.1900  389.1400
2    376.7633  389.1400
3    376.7633  387.0899
4    381.0800  389.4700
..        ...       ...
495  874.6975  899.7475
496  881.9510  905.4800
497  893.7000  905.9200
498  893.7000  911.8800
499  898.7000  913.3175

[500 rows x 2 columns]

In [13]:
# consider using a lower percentiles mean
multiday_volatility = (df_lh['high'] - df_lh['low'])/df_lh['low']
initial_multiday_pertentage = np.percentile(multiday_volatility, [60, 55, 50]).mean()
initial_multiday_pertentage

np.float64(0.03152821761885067)

Rate determination <br>
6 possibilities

1.   upper < low  (price is over the band)
2.   lower > high (price is below the band)
3.   high > upper > low > lower (price cross upper band)
4.   upper > high > lower > low (price cross lower band)
5.   upper > high & low > lower (price inside the band)
6.   high > upper & lower > low (price so volatile, cross the whole band)

In [14]:
# prepare the dataframe
df_ratio = df_hl.dropna()
df_ratio["UPPER"] = UPPER
df_ratio["LOWER"] = LOWER
df_ratio.dropna(inplace=True)
#calculate the ratio
# df_ratio_temp.query("ratio2 == ratio2") # to hack the fact that value == NaN will always be false
rate1 = np.where(df_ratio["UPPER"] < df_ratio["Low"],initial_multiday_pertentage*2 , 0) # extreme uptick
rate2 = np.where(df_ratio["LOWER"] > df_ratio["High"],initial_multiday_pertentage*2 , 0) # extreme downward
rate3 = np.where((df_ratio['High'] > df_ratio['UPPER']) & (df_ratio['UPPER'] >  df_ratio['Low'] ) & (df_ratio['LOWER'] <  df_ratio['Low'] ), initial_multiday_pertentage*1.5, 0) # start to go up
rate4 = np.where((df_ratio['UPPER'] > df_ratio['High']) & (df_ratio['High'] > df_ratio['LOWER']) & (df_ratio['LOWER'] > df_ratio['Low'] ), initial_multiday_pertentage*1.5, 0) # start to go down
# rate = np.vstack((rate1, rate2))
rate5 = np.where((df_ratio['UPPER'] > df_ratio['High']) & (df_ratio['Low'] > df_ratio['LOWER']), initial_multiday_pertentage, 0)
rate6 = np.where((df_ratio['High'] > df_ratio['UPPER']) & (df_ratio['LOWER'] > df_ratio['Low']), initial_multiday_pertentage, 0)
rate = rate1 + rate2 + rate3 + rate4 + rate5 +rate6

In [15]:
df_ratio['rate'] = rate
df_ratio

                High      Low     UPPER     LOWER    rate
Date
2024-02-22  395.6000  389.000  386.4681  382.3628  0.0631
2024-02-23  396.7900  389.210  387.3696  382.8318  0.0631
2024-02-26  396.0600  388.820  388.0950  383.1255  0.0631
2024-02-27  395.9000  389.330  388.7382  383.3455  0.0631
2024-02-28  393.2600  387.000  389.5155  383.5137  0.0473
...              ...      ...       ...       ...     ...
2025-12-19  899.7475  881.951  896.0873  801.1496  0.0473
2025-12-22  905.4800  894.840  903.0723  801.8038  0.0473
2025-12-23  905.9200  893.700  909.7019  802.4358  0.0315
2025-12-24  911.8800  898.700  916.3317  803.5202  0.0315
2025-12-26  913.3175  905.305  922.3261  804.6305  0.0315

[464 rows x 5 columns]

In [16]:
# initial values
flag = 1
buy_signal = [np.nan]; sell_signal = [np.nan]
buyline = [np.nan]; sellline = [np.nan]
ceiling = 0 
bottom = df_ratio['Low'][0]

/var/folders/3d/l9hvct0s7ld_cxrj3cwvwpdh0000gn/T/ipykernel_9537/3793126256.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

In [17]:
for i in range(len(df_ratio)-1):
    if flag == 1: # seeking buying oppotunity
        sell_signal.append(np.nan)
        sellline.append(np.nan)
        buyline.append(bottom * (1 + df_ratio['rate'][i]))
        bottom = min(bottom, df_ratio['Low'][i+1])
        if df_ratio["High"][i+1] > buyline[-1] > df_ratio["Low"][i+1]: # order hit the next day
            flag = -1
            buy_signal.append(buyline[-1])
            ceiling = df_ratio["High"][i+1]
        else:
            buy_signal.append(np.nan)


    elif flag == -1: # seeking selling oppotunity
        buy_signal.append(np.nan)
        buyline.append(np.nan)
        sellline.append(ceiling * (1 - df_ratio['rate'][i]))
        ceiling = max(ceiling, df_ratio['High'][i+1])
        if df_ratio["High"][i+1] > sellline[-1] > df_ratio["Low"][i+1]: # sell hit the next day
            flag = 1
            sell_signal.append(sellline[-1])
            bottom = df_ratio["Low"][i+1]
        else:
            sell_signal.append(np.nan)

/var/folders/3d/l9hvct0s7ld_cxrj3cwvwpdh0000gn/T/ipykernel_9537/37544699.py:5: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/var/folders/3d/l9hvct0s7ld_cxrj3cwvwpdh0000gn/T/ipykernel_9537/37544699.py:6: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/var/folders/3d/l9hvct0s7ld_cxrj3cwvwpdh0000gn/T/ipykernel_9537/37544699.py:7: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/var/folders/3d/l9hvct0s7ld_cxrj3cwvwpdh0000gn/T/ipykernel_9537/37544699.py:10: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/var/folders/3d/l9hvct0s7ld_cxrj3cwvwpdh0000gn/T/ipykernel_9537/37544699.py:18: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/var/folders/3d/l9hvct0s7ld_cxrj3cwvwpdh0000gn/T/ipykernel_9537/37544699.py:19: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/var/folders/3d/l9hvct0s7ld_cxrj3cwvwpdh0000gn/T/ipykernel_9537/37544699.py:20: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

/var/folders/3d/l9hvct0s7ld_cxrj3cwvwpdh0000gn/T/ipykernel_9537/37544699.py:23: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

In [18]:
df_ratio['buy line'] = buyline
df_ratio['buy signal'] = buy_signal
df_ratio['sell line'] = sellline
df_ratio['sell signal'] = sell_signal
df_ratio.head(8)

,High,Low,UPPER,LOWER,rate,buy line,buy signal,sell line,sell signal
Date,,,,,,,,,
2024-02-22,395.60,389.00,386.4681,382.3628,0.0631,NaN,NaN,NaN,NaN
2024-02-23,396.79,389.21,387.3696,382.8318,0.0631,413.5290,NaN,NaN,NaN
2024-02-26,396.06,388.82,388.0950,383.1255,0.0631,413.5290,NaN,NaN,NaN
2024-02-27,395.90,389.33,388.7382,383.3455,0.0631,413.3376,NaN,NaN,NaN
2024-02-28,393.26,387.00,389.5155,383.5137,0.0473,413.3376,NaN,NaN,NaN
2024-02-29,395.98,385.67,389.9553,383.4567,0.0473,405.3021,NaN,NaN,NaN
2024-03-01,391.04,385.25,390.2498,383.3703,0.0473,403.9092,NaN,NaN,NaN
2024-03-04,396.57,386.20,390.9811,383.6429,0.0473,403.4694,NaN,NaN,NaN

In [19]:
df = pd.concat([df_ratio, df_polygon[["Open", "Adj Close"]]], axis=1)
df.head(50)

,High,Low,UPPER,LOWER,rate,buy line,buy signal,sell line,sell signal,Open,Adj Close
Date,,,,,,,,,,,
2023-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.52,386.41
2023-12-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,385.57,385.77
2024-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,383.00,388.30
2024-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,383.88,381.79
2024-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,383.55,382.95
2024-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.92,386.44
2024-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,385.97,388.86
2024-01-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.60,383.74
2024-01-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.35,381.96
2024-01-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380.89,379.75
2024-01-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,383.34,377.75
2024-01-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,378.36,380.45
2024-01-17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,375.20,377.18
2024-01-18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380.33,376.91
2024-01-19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,376.73,382.20
2024-01-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,386.36,385.96
2024-01-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,379.98,380.77
2024-01-24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.81,379.40
2024-01-25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,382.69,382.70
2024-01-26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,378.65,377.79
2024-01-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,375.89,380.56
2024-01-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.00,386.87
2024-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,386.00,384.01
2024-02-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.43,383.85
2024-02-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.80,387.86
2024-02-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.60,383.02
2024-02-06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,383.02,384.99
2024-02-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,385.31,386.66
2024-02-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,386.00,385.04
2024-02-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,384.77,384.26
2024-02-12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,385.00,392.64
2024-02-13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,387.59,378.75
2024-02-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380.88,378.04
2024-02-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,379.42,385.42
2024-02-16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,383.24,384.44
2024-02-20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380.95,384.52
2024-02-21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.84,388.27
2024-02-22,395.60,389.00,386.4681,382.3628,0.0631,NaN,NaN,NaN,NaN,389.23,390.47
2024-02-23,396.79,389.21,387.3696,382.8318,0.0631,413.5290,NaN,NaN,NaN,390.00,391.05
2024-02-26,396.06,388.82,388.0950,383.1255,0.0631,413.5290,NaN,NaN,NaN,391.05,390.22
2024-02-27,395.90,389.33,388.7382,383.3455,0.0631,413.3376,NaN,NaN,NaN,392.26,390.81
2024-02-28,393.26,387.00,389.5155,383.5137,0.0473,413.3376,NaN,NaN,NaN,387.19,393.18
2024-02-29,395.98,385.67,389.9553,383.4567,0.0473,405.3021,NaN,NaN,NaN,395.22,389.05
2024-03-01,391.04,385.25,390.2498,383.3703,0.0473,403.9092,NaN,NaN,NaN,389.63,388.10
2024-03-04,396.57,386.20,390.9811,383.6429,0.0473,403.4694,NaN,NaN,NaN,388.81,392.25
2024-03-05,397.49,390.31,391.6000,383.8770,0.0473,403.4694,NaN,NaN,NaN,390.72,390.91
2024-03-06,395.29,384.52,391.8781,383.9543,0.0473,403.4694,NaN,NaN,NaN,395.00,389.57
2024-03-07,394.51,387.06,392.0679,383.9601,0.0473,402.7048,NaN,NaN,NaN,391.90,388.43
2024-03-08,395.62,386.71,392.3205,383.9637,0.0473,402.7048,NaN,NaN,NaN,388.73,386.99
2024-03-11,386.41,381.42,392.1303,383.6794,0.0473,402.7048,NaN,NaN,NaN,385.67,386.16

In [20]:
fig = go.Figure()

fig = go.Figure(data=go.Ohlc(x=df_polygon.index,
                    open=df_polygon['Open'],
                    high=df_polygon['High'],
                    low=df_polygon['Low'],
                    close=df_polygon['Adj Close'],
                    name='K-chart'))


fig.add_trace(go.Scatter(  # 
    x=df.index, 
    y=df['buy line'],               
    mode='lines', # line mode          
    name='Track buy signal',
    line=dict(color='royalblue', width=1.5))) # or color='#00ffff'

fig.add_trace(go.Scatter(  # 
    x=df.index, 
    y=df['sell line'],               
    mode='lines', # line mode              
    name='Track sell signal',
    line=dict(color='firebrick', width=1.5))) # or color='#0000ff'

fig.show()